# This is a workflow for bumping the CLI version references in the Formula and creating a PR with the changes.
#
# It is configured to be triggered by repository dispatch events which come from outside of this repository.
# It requires write access to the repository by providing a personal access token (PAT) with `repo` scope.
#
# The `event_type` parameter is expected to be `trigger-bump-formula-pr`.
# The `client_payload` parameter is expected to contain the following data:
#   * `CLI_version`: a string containing the Phylum CLI version to include
#                    in the formula, with or without the leading `v` (e.g., v4.7.0)
#
# Here is an example repository dispatch event, triggered with `curl` from the command line:
#
# curl \
#   -X POST \
#   --fail-with-body \
#   -H "Accept: application/vnd.github+json" \
#   -H "X-GitHub-Api-Version: 2022-11-28" \
#   -H "Authorization: token <PAT>" \
#   -d '{"event_type":"trigger-bump-formula-pr","client_payload":{"CLI_version":"v4.7.0"}}' \
#   https://api.github.com/repos/phylum-dev/homebrew-cli/dispatches
#
# References:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
# https://docs.github.com/en/rest/repos/repos#create-a-repository-dispatch-event
---
name: Bump Formula and Create PR

on:
  repository_dispatch:
    types: [trigger-bump-formula-pr]

jobs:
  bump:
    name: Bump Formula and create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          # This PAT is for the `phylum-bot` account and only has the `public_repo` scope to limit privileges.
          token: ${{ secrets.GH_RELEASE_PAT }}

      # This GPG key is for the `phylum-bot` account and used in order to ensure commits are signed/verified
      - name: Import GPG key for bot account
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PHYLUM_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PHYLUM_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          debug: true
          # This PAT is for the `phylum-bot` account and only has the `public_repo` scope to limit privileges.
          token: ${{ secrets.GH_RELEASE_PAT }}

      - name: Create a PR with new formula URL and SHA
        env:
          HOMEBREW_DEVELOPER: "1"
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        run: |
          git remote set-url origin git@github.com:"$GITHUB_REPOSITORY".git
          CLI_VER_WITHOUT_v=$(echo ${{ github.event.client_payload.CLI_version }} | sed 's/v//')
          printf "CLI_VER_WITHOUT_v: %s\n" "$CLI_VER_WITHOUT_v"
          brew bump-formula-pr --version "$CLI_VER_WITHOUT_v" --no-fork --no-browse --no-audit --debug --verbose phylum
