# This is a workflow for bumping the CLI version references in the Formula and creating a PR with the changes.
#
# It is configured to be triggered by repository dispatch events which come from outside of this repository.
# It requires write access to the repository by providing a personal access token (PAT) with `repo` scope.
#
# The `event_type` parameter is expected to be `trigger-bump-formula-pr`.
# The `client_payload` parameter is expected to contain the following data:
#   * `CLI_version`: a string containing the Phylum CLI version to include
#                    in the formula, with or without the leading `v` (e.g., v4.7.0)
#
# Here is an example repository dispatch event, triggered with `curl` from the command line:
#
# curl \
#   -X POST \
#   --fail-with-body \
#   -H "Accept: application/vnd.github+json" \
#   -H "X-GitHub-Api-Version: 2022-11-28" \
#   -H "Authorization: token <PAT>" \
#   -d '{"event_type":"trigger-bump-formula-pr","client_payload":{"CLI_version":"v4.7.0"}}' \
#   https://api.github.com/repos/phylum-dev/homebrew-cli/dispatches
#
# References:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
# https://docs.github.com/en/rest/repos/repos#create-a-repository-dispatch-event
---
name: Bump Formula and Create PR

on:
  repository_dispatch:
    types: [trigger-bump-formula-pr]

jobs:
  bump:
    name: Bump Formula and create PR
    runs-on: ubuntu-latest
    env:
      CLI_VER: ${{ github.event.client_payload.CLI_version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # This GPG key is for the `phylum-bot` account and used in order to ensure commits are signed/verified
      - name: Import GPG key for bot account
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PHYLUM_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PHYLUM_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update URL and SHA256 values
        # NOTE: The `archive/refs/tags` link is used instead of the `tarball_url` provided by the release API because
        #       the hashes between the two are (currently) different, even though the extracted contents are the same.
        #       The `archive/refs/tags` link format is used by the formula and is therefore the one downloaded here.
        #       Reference: https://github.com/community/community/discussions/45830
        # NOTE: The git user name/email used for commits is already configured, by crazy-max/ghaction-import-gpg action.
        run: |
          curl -sSfLO "https://github.com/phylum-dev/cli/archive/refs/tags/${CLI_VER}.tar.gz"
          TARBALL_SHA=$(sha256sum "${CLI_VER}.tar.gz" | cut -d' ' -f1)
          sed -E -i'.bak' "/^  url /s/\/v.*.tar.gz/\/${CLI_VER}.tar.gz/" Formula/phylum.rb
          sed -E -i'.bak' "/^  sha256 /s/.*/  sha256 \"${TARBALL_SHA}\"/" Formula/phylum.rb
          git add Formula/phylum.rb
          git commit -m "phylum ${CLI_VER#v}"
          git push --force origin "HEAD:bump-phylum-${CLI_VER#v}"

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          # This PAT is for the `phylum-bot` account and only has the `public_repo` scope to limit privileges.
          github-token: ${{ secrets.GH_RELEASE_PAT }}
          script: |
            var cli_ver_no_v = process.env.CLI_VER;
            while (cli_ver_no_v.charAt(0) === 'v'){
              cli_ver_no_v = cli_ver_no_v.substring(1);
            }
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "bump-phylum-" + cli_ver_no_v,
              base: context.ref,
              title: "phylum " + cli_ver_no_v,
              body: "Reminder: It is better to wait for the first 3 jobs "
                  + "(2 for `build-bottles` and 1 for `brew-bottle`) to "
                  + "complete before approving this PR because the PR will "
                  + "be updated by that 4th job with a new commit that updates "
                  + "the formula to include the new bottle `root_url` and `sha256` "
                  + "values. Additionally, this PR should not be merged to `main` "
                  + "until _after_ the bottles have been successfully published.",
            });
            console.log(response);
