name: Publish Bottles
on:
  pull_request:
    paths:
      - Formula/*.rb

jobs:
  build-bottles:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - [self-hosted, macos, arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        # NOTE: A specific commit is used here b/c this action does not
        #       publish tags and the current `master` appears to be broken.
        uses: Homebrew/actions/setup-homebrew@449449e64aaa5faac0d24229a2ffba32438e4b63

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae

      - name: Upload bottles as artifact
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: '*.bottle.*'

  brew-bottle:
    runs-on: ubuntu-latest
    needs: build-bottles
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@449449e64aaa5faac0d24229a2ffba32438e4b63

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up git
        uses: Homebrew/actions/git-user-config@449449e64aaa5faac0d24229a2ffba32438e4b63

      - name: Download bottle artifacts
        uses: actions/download-artifact@v3
        with:
          name: bottles

      - name: Merge bottles
        run: brew bottle --merge --write --debug *.bottle.json

      - name: Push commits
        run: git push

  publish-bottles:
    runs-on: ubuntu-latest
    needs: brew-bottle
    environment: release
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@449449e64aaa5faac0d24229a2ffba32438e4b63

      - name: Download bottle artifacts
        uses: actions/download-artifact@v3
        with:
          name: bottles

      - name: Upload bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
        run: brew pr-upload --debug --upload-only
