name: Publish Bottles
on:
  pull_request:
    paths:
      - Formula/*.rb

jobs:
  build-bottles:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - [self-hosted, macos, arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew self-hosted
        if: contains(${{ matrix.os }}, 'self-hosted')
        env:
          # This environment variable is not documented, but is needed to
          # prevent failures and destructive actions added in this commit:
          # https://github.com/Homebrew/actions/commit/616a563beaa0715ddebbb39a331224af1b46fdaa
          GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED: 1
        uses: Homebrew/actions/setup-homebrew@master
        with:
          debug: true

      - name: Set up Homebrew
        if: contains(${{ matrix.os }}, 'self-hosted') == false
        uses: Homebrew/actions/setup-homebrew@master
        with:
          debug: true

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae

      - name: Upload bottles as artifact
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: '*.bottle.*'

  brew-bottle:
    runs-on: ubuntu-latest
    needs: build-bottles
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          debug: true

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Download bottle artifacts
        uses: actions/download-artifact@v3
        with:
          name: bottles

      - name: Merge bottles
        run: brew bottle --merge --write --debug ./*.bottle.json

      - name: Push commits
        run: git push

  publish-bottles:
    runs-on: ubuntu-latest
    needs: brew-bottle
    environment: release
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          debug: true

      - name: Download bottle artifacts
        uses: actions/download-artifact@v3
        with:
          name: bottles

      - name: Upload bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
        run: brew pr-upload --debug --upload-only
